### PR TITLE
Added binary tree, changed .gitignore for pycharm

### PR DESCRIPTION
**Pull request by VladislavBakshanskij**
I added the data structure as a binary tree, with appropriate methods that include tree traversal with a description of how they work and examples of use. Added corresponding tests to trees.

The file was also changed .gitignore to ignore files in Pycharm.

### CODE REVIEW

**Comment by VladislavBakshanskij** [comment]
The tree has been implemented to indicate search performance in simple tree.

**Comment by ekinkaradag** [comment]
@VladislavBakshanskij First of all, nice to meet you and thank you so much for your interest. I will review your code as soon as possible.

**Comment by VladislavBakshanskij** [comment]
sorry for my mistakes in english. I'm not good at writing comments. and thanks for helping YOU.

**Comment by ekinkaradag** [comment]
Thank you so much for your effort and your great work 👍 . I am merging the pull request now.

**Comment by VladislavBakshanskij** [comment]
Did you understand my code?

**Comment by ekinkaradag** [comment]
Yes, I did. However, there are more functionalities that could be implemented. So, if you ever want to contribute again, please feel free to do so :)

**Comment by VladislavBakshanskij** [comment]
I agree.  You can, for example, implement deletions.  But it will most likely be.  Perhaps on the weekend here I myself am just writing in Java, and if there are more optimal possibilities for using Python, you can tell me, accordingly, to supplement them with functions that can be implemented

**Comment by VladislavBakshanskij** [comment]
👀👀👀👀👀

**Pull request merged**
